version: "3"
services:
  nginx:
    build:
      context: ./develop/nginx
    volumes:
      - ../:/var/www
      - ./develop/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./develop/nginx/ssl:/etc/ssl
      - ./log/nginx/:/var/log/nginx/
    depends_on:
      - php-fpm
    ports:
      - 8081:80
      - 443:443
  php-fpm:
    build:
      context: ./develop/php-frm
    volumes:
      - ../:/var/www
  php-cli:
    build:
      context: ./develop/php-cli
    volumes:
      - ../:/var/www
    tty: true
  node:
    image: node:alpine
    volumes:
      - ../:/var/www
    working_dir: /var/www
    tty: true
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./db-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db-data:/var/lib/mysql/data
    env_file:
      - ./db.env
    depends_on:
      - php-fpm
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
      - php-fpm

volumes:
  db-data:
